export { packRgba, parseHex, toHex, unpackRgba } from './domain/color.js';
export type { Color, ColorParseError, Rgba } from './domain/color.js';
export { err, ok } from './result.js';
export type { Result } from './result.js';
export { MAX_CANVAS_SIZE, PixelBuffer } from './domain/pixel-buffer.js';
export { createSprite } from './domain/sprite.js';
export type { BlendMode, InvalidSizeError, Layer, Sprite, SpriteOptions } from './domain/sprite.js';
export { createSequentialIdGenerator } from './ports/id-generator.js';
export type { IdGenerator } from './ports/id-generator.js';
export { traceLine } from './algorithms/line.js';
export type { PlotFn } from './algorithms/line.js';
export { traceEllipse, traceRect } from './algorithms/shapes.js';
export { colorsWithinTolerance, floodFillSpans } from './algorithms/flood-fill.js';
export type { FillMode, FillOptions, SpanFn } from './algorithms/flood-fill.js';
export { unionRects } from './domain/rect.js';
export type { Rect } from './domain/rect.js';
export { PixelPatchCommand } from './history/command.js';
export type { Command } from './history/command.js';
export { DEFAULT_HISTORY_BUDGET_BYTES, HistoryManager } from './history/history-manager.js';
export type { HistoryStep } from './history/history-manager.js';
export { PatchRecorder } from './history/patch-recorder.js';
export { applyPatch, createPatch, patchSizeBytes, revertPatch } from './history/pixel-patch.js';
export type { PixelPatch, RectPatch, SparsePatch } from './history/pixel-patch.js';
